/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoSentryBadEventHandlerRouteImport } from './routes/demo.sentry.bad-event-handler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryBadEventHandlerRoute =
  DemoSentryBadEventHandlerRouteImport.update({
    id: '/demo/sentry/bad-event-handler',
    path: '/demo/sentry/bad-event-handler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/sentry/bad-event-handler': typeof DemoSentryBadEventHandlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/sentry/bad-event-handler': typeof DemoSentryBadEventHandlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/sentry/bad-event-handler': typeof DemoSentryBadEventHandlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/demo/store' | '/demo/sentry/bad-event-handler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/demo/store' | '/demo/sentry/bad-event-handler'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/sentry/bad-event-handler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoSentryBadEventHandlerRoute: typeof DemoSentryBadEventHandlerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/bad-event-handler': {
      id: '/demo/sentry/bad-event-handler'
      path: '/demo/sentry/bad-event-handler'
      fullPath: '/demo/sentry/bad-event-handler'
      preLoaderRoute: typeof DemoSentryBadEventHandlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoSentryBadEventHandlerRoute: DemoSentryBadEventHandlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
